apiVersion: batch/v1
kind: Job
metadata:
  name: fppss-rest-api-migrations
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: fppss-rest-api-migrations
    spec:
      restartPolicy: Never
      containers:
      - name: fppss-rest-api-migrations
        image: ghcr.io/2110781006/fppss-rest-api-migrations:latest
        env:
        - name: FPPSS_KEY
          valueFrom:
            configMapKeyRef:
              name: fppss-rest-api
              key: fppss_key
        - name: FPPSS_DB_URL
          valueFrom:
            configMapKeyRef:
              name: fppss-rest-api
              key: fppss_db_url
        - name: FPPSS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fppss-db-secret
              key: password
        - name: FPPSS_DB_USER
          valueFrom:
            secretKeyRef:
              name: fppss-db-secret
              key: user
