---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: fppss-rest-api
  namespace: flux-system
spec:
  image: ghcr.io/2110781006/fppss-rest-api
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: fppss-datacollector
  namespace: flux-system
spec:
  image: ghcr.io/2110781006/fppss-datacollector
  interval: 6m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: fppss-frontend
  namespace: flux-system
spec:
  image: ghcr.io/2110781006/fppss-frontend
  interval: 6m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: fppss-rest-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fppss-rest-api
  policy:
    semver:
      range: '>=0.0.0 <1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: fppss-datacollector
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fppss-datacollector
  policy:
    semver:
      range: '>=0.0.0 <1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: fppss-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fppss-frontend
  policy:
    semver:
      range: '>=0.0.0 <1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./config/kubernetes
    strategy: Setters
