---
apiVersion: v1
kind: Service
metadata:
  name: fppss-db
  namespace: fppss-energy
  labels:
    app: fppss-energy
spec:
  selector:
    component: fppss-db
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  type: ClusterIP
