apiVersion: apps/v1
kind: Deployment
metadata:
  name: fppss-frontend
  namespace: fppss-energy
  labels:
    app: fppss-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fppss-frontend
  template:
    metadata:
      labels:
        app: fppss-frontend
    spec:
      containers:
      - name: fppss-frontend
        image: nginx:latest
        ports:
        - containerPort: 80
