apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fppss-frontend
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fppss-frontend
            port:
              number: 80
