apiVersion: v1
kind: Service
metadata:
  name: fppss-frontend
  namespace: fppss-energy
spec:
  type: ClusterIP
  selector:
    app: fppss-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
