---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fppss-db
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fppss-sso
spec:
  storageClassName: local-path
