apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fppss-rest-api
  namespace: fppss-energy
spec:
  rules:
  - http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: fppss-rest-api
            port:
              number: 80
