apiVersion: v1
kind: Service
metadata:
  name: fppss-rest-api
  namespace: fppss-energy
spec:
  type: ClusterIP
  selector:
    app: fppss-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
