---
apiVersion: v1
kind: Service
metadata:
  name: fppss-frontend
  namespace: fppss-energy
  labels:
    app: fppss-energy
spec:
  selector:
    component: fppss-frontend
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
