---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fppss-db
  namespace: fppss-energy
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fppss-sso
  namespace: fppss-energy
spec:
  storageClassName: local-path
