apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-redirect
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-allow-origin
  namespace: default
spec:
  headers:
    accessControlAllowOriginList:
      - "https://fppss-demo-sso.thomasst.xyz"
      - "https://fppss-demo.thomasst.xyz"
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - "GET"
      - "PUT"
      - "DELETE"
      - "POST"
    accessControlAllowHeaders:
      - "X-Requested-With"
      - "Content-Type"
      - "Authorization"
      - "Origin"
      - "Accept"
      - "Access-Control-Request-Method"
      - "Access-Control-Request-Headers"
    accessControlMaxAge: 0
    addVaryHeader: true
