---
apiVersion: v1
kind: Service
metadata:
  name: fppss-rest-api
  namespace: fppss-energy
  labels:
    app: fppss-energy
spec:
  selector:
    component: fppss-rest-api
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
