apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fppss-rest-api.fullname" . }}
  labels:
    {{- include "fppss-rest-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fppss-rest-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fppss-rest-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fppss-rest-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
          env:
          - name: FPPSS_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ include "fppss-rest-api.fullname" . }}
                key: fppss_key
          - name: FPPSS_DB_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "fppss-rest-api.fullname" . }}
                key: fppss_db_url
          - name: FPPSS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fppss-db-secret
                key: password
          - name: FPPSS_DB_USER
            valueFrom:
              secretKeyRef:
                name: fppss-db-secret
                key: user
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
