apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - datacollector
  - db
  - frontend
  - rest-api
  - sso

resources:
- deployrestart-cronjob.yaml # used as workaround for a bug with datacollector 

namespace: fppss-energy
